[TEMP][MacOS] Patch upstream code to fix a build error.
Assuming this doesn't happen to the upstream build; not sure why ATM.

Error:

 ../../content/browser/accessibility/accessibility_event_recorder_mac.mm:112:8: error: call to implicitly-deleted copy constructor of 'content::AccessibilityTreeFormatterMac'
    auto formatter = AccessibilityTreeFormatterMac();
         ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../content/browser/accessibility/accessibility_tree_formatter_mac.h:17:7: note: copy constructor of 'AccessibilityTreeFormatterMac' is implicitly deleted because base class 'ui::AXTreeFormatterBase' has a deleted copy constructor
      : public ui::AXTreeFormatterBase {
        ^
  ../../ui/accessibility/platform/inspect/ax_tree_formatter_base.h:25:3: note: 'AXTreeFormatterBase' has been explicitly marked deleted here
    AXTreeFormatterBase(const AXTreeFormatterBase&) = delete;
    ^
  1 error generated.

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/ca1eda1828237d6e2938afd5d1a47fda083a5b8c

commit ca1eda1828237d6e2938afd5d1a47fda083a5b8c
Author: Alexander Surkov <asurkov@igalia.com>
Date:   Thu Dec 9 18:44:24 2021 +0000

    ax_tools: unify event targets dumping in the mac event recorder

    Mac event recorder should reuse tree formatter to dump event targets:
    * share common code paths
    * allows to manage which event target properties shall be dumped.